
Resources:
  AssetDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: lambda-origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: true
        Origins:
          - Id: lambda-origin
            DomainName: !GetAtt AssetLambda.FunctionUrl
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
