Resources:
  AssetLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: zota-ssap-lambda
      PackageType: Image
      Code:
        ImageUri: 820064186646.dkr.ecr.ap-southeast-1.amazonaws.com/zota-ssap-repo:1.0
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 15
      MemorySize: 512

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: zota-ssap-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub "arn:aws:s3:::irfath-zota-bucket-${AWS::AccountId}/*"
