#FROM public.ecr.aws/lambda/go:1
#COPY main ${LAMBDA_TASK_ROOT}
#CMD ["main"]

#FROM public.ecr.aws/lambda/provided:al2
#COPY main /var/task/main
#CMD ["main"] 


FROM public.ecr.aws/lambda/go:1
COPY main ${LAMBDA_TASK_ROOT}
CMD ["main"]